version: '3.7'

services:
  todolist_database:
    image: mariadb
    container_name: todolist_database
    environment:
      - MYSQL_ROOT_PASSWORD=${TYPEORM_PASSWORD}
      - MYSQL_DATABASE=${TYPEORM_DATABASE}
    volumes:
      - todolist_volume:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - todolist_network

networks:
  todolist_network:
    driver: bridge

volumes:
  todolist_volume:
    driver: local
